services:
  db:
    container_name: db
    environment:
      - SQLD_NODE=primary
      - SQLD_HTTP_AUTH=basic:${DB_AUTH_TOKEN:-default}
      - SQLD_ENABLE_BOTTOMLESS_REPLICATION=${MINIO_BACKUP:-false}
      - LIBSQL_BOTTOMLESS_ENDPOINT=${MINIO_ENDPOINT}
      - LIBSQL_BOTTOMLESS_AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - LIBSQL_BOTTOMLESS_AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
      - LIBSQL_BOTTOMLESS_BUCKET=sssvpn-${NODE_ENV}
      - LIBSQL_BOTTOMLESS_AWS_DEFAULT_REGION=${MINIO_REGION}
      - RUST_LOG=info,bottomless=info
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 5s
      test: "sqld --version || exit 1"
      timeout: 5s
    image: ghcr.io/tursodatabase/libsql-server:v0.24.26
    ports:
      - 8888:8080
      - 5001:5001
    restart: unless-stopped
    volumes:
      - libsql:/var/lib/sqld

  sssvpn:
    build:
      args:
        - SENTRY_PROJECT=${SENTRY_PROJECT}
        - SENTRY_DSN=${SENTRY_DSN}
        - SENTRY_TOKEN=${SENTRY_TOKEN}
        - SOURCE_COMMIT=${SOURCE_COMMIT}
        - SITE_URL=${SITE_URL}
      context: .
      dockerfile: Dockerfile
    container_name: sssvpn
    depends_on:
      db:
        condition: service_healthy
    environment:
      - API_TOKEN=${API_TOKEN}
      - DB_REMOTE=${DB_REMOTE:-http://db:8080}
      - DB_AUTH_TOKEN=${DB_AUTH_TOKEN:-default}
      - GTM_ID=${GTM_ID}
      - LOG_LEVEL=${LOG_LEVEL}
    healthcheck:
      interval: 1m
      retries: 5
      start_period: 10s
      test: "curl -fs -o /dev/null http://localhost:4321"
      timeout: 5s
    ports:
      - 4321:4321
    restart: unless-stopped

volumes:
  libsql:
