services:
  sss-vpn:
    container_name: sss-vpn
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_CONFIG=${SECRET_CONFIG}
      - PUBLIC_CONFIG=${PUBLIC_CONFIG}
    ports:
      - 4321:4321
    restart: unless-stopped
