name: Build & Test & Lint

on: [push]

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install packages
        run: pnpm install --frozen-lock

      - name: Build
        run: pnpm build

      - name: Format & Lint
        run: pnpm lint

      - name: Test
        run: pnpm test:all
