name: Build & Test & Lint

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install packages
        run: pnpm install --frozen-lock
      - name: Format & Lint
        run: pnpm check && pnpm lint
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test:all
